// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHome.Data;

#nullable disable

namespace SmartHome.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414214541_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Models.ClassNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<int?>("MeasureUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("class_node", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsTerminal = false,
                            Name = "Умный дом",
                            ShortName = "smart-home",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsTerminal = false,
                            Name = "Освещение",
                            ParentId = 1,
                            ShortName = "lighting",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            IsTerminal = false,
                            Name = "Климат-контроль",
                            ParentId = 1,
                            ShortName = "climate-control",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            IsTerminal = false,
                            Name = "Источники света",
                            ParentId = 2,
                            ShortName = "light-sources",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            IsTerminal = false,
                            Name = "Управление освещением",
                            ParentId = 2,
                            ShortName = "lighting-control",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 6,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Датчики освещенности",
                            ParentId = 2,
                            ShortName = "light-sensors",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 7,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "LED лампы",
                            ParentId = 4,
                            ShortName = "led-lamps",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "RGB лампы",
                            ParentId = 4,
                            ShortName = "rgb-lamps",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 9,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Умные ленты",
                            ParentId = 4,
                            ShortName = "smart-strips",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Выключатели",
                            ParentId = 5,
                            ShortName = "switches",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 11,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Панели управления",
                            ParentId = 5,
                            ShortName = "control-panels",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 12,
                            IsTerminal = false,
                            Name = "Отопление",
                            ParentId = 3,
                            ShortName = "heating",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 13,
                            IsTerminal = false,
                            Name = "Охлаждение",
                            ParentId = 3,
                            ShortName = "cooling",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 14,
                            IsTerminal = false,
                            Name = "Вентиляция",
                            ParentId = 3,
                            ShortName = "ventilation",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 15,
                            IsTerminal = false,
                            Name = "Датчики климата",
                            ParentId = 3,
                            ShortName = "climate-sensors",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 16,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Термостаты",
                            ParentId = 12,
                            ShortName = "thermostats",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Радиаторные клапаны",
                            ParentId = 12,
                            ShortName = "radiator-valves",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            IsTerminal = true,
                            MeasureUnitId = 2,
                            Name = "Тёплый пол",
                            ParentId = 12,
                            ShortName = "floor-heating",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 19,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Кондиционеры",
                            ParentId = 13,
                            ShortName = "air-conditioners",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 20,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Вентиляторы",
                            ParentId = 13,
                            ShortName = "fans",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 21,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Рекуператоры",
                            ParentId = 14,
                            ShortName = "recuperators",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 22,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Вытяжные системы",
                            ParentId = 14,
                            ShortName = "exhaust-systems",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 23,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Датчики температуры",
                            ParentId = 15,
                            ShortName = "temperature-sensors",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 24,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Датчики влажности",
                            ParentId = 15,
                            ShortName = "humidity-sensors",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 25,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "CO2 датчики",
                            ParentId = 15,
                            ShortName = "co2-sensors",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("SmartHome.Models.MeasureUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("measure_unit", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Штука",
                            ShortName = "шт."
                        },
                        new
                        {
                            Id = 2,
                            Name = "Комплект",
                            ShortName = "компл."
                        },
                        new
                        {
                            Id = 3,
                            Name = "Зона",
                            ShortName = "зона"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Канал",
                            ShortName = "канал"
                        });
                });

            modelBuilder.Entity("SmartHome.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassNodeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ClassNodeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassNodeId = 7,
                            Name = "Xiaomi Smart LED Bulb",
                            ShortName = "xiaomi-led-bulb"
                        },
                        new
                        {
                            Id = 2,
                            ClassNodeId = 8,
                            Name = "Philips Hue White and Color",
                            ShortName = "philips-hue-color"
                        },
                        new
                        {
                            Id = 3,
                            ClassNodeId = 10,
                            Name = "Aqara Wall Switch H1",
                            ShortName = "aqara-switch-h1"
                        },
                        new
                        {
                            Id = 4,
                            ClassNodeId = 16,
                            Name = "Google Nest Thermostat",
                            ShortName = "nest-thermostat"
                        },
                        new
                        {
                            Id = 5,
                            ClassNodeId = 23,
                            Name = "Xiaomi Temperature and Humidity Sensor",
                            ShortName = "xiaomi-temp-humidity"
                        });
                });

            modelBuilder.Entity("SmartHome.Models.ClassNode", b =>
                {
                    b.HasOne("SmartHome.Models.MeasureUnit", "MeasureUnit")
                        .WithMany("ClassNodes")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartHome.Models.ClassNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MeasureUnit");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SmartHome.Models.Product", b =>
                {
                    b.HasOne("SmartHome.Models.ClassNode", "ClassNode")
                        .WithMany("Products")
                        .HasForeignKey("ClassNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassNode");
                });

            modelBuilder.Entity("SmartHome.Models.ClassNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartHome.Models.MeasureUnit", b =>
                {
                    b.Navigation("ClassNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
