// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHome.Data;

#nullable disable

namespace SmartHome.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512231644_AddProductParameters")]
    partial class AddProductParameters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Models.ClassNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<int?>("MeasureUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("class_node", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsTerminal = false,
                            Name = "Умный дом",
                            ShortName = "smart-home",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsTerminal = false,
                            Name = "Освещение",
                            ParentId = 1,
                            ShortName = "lighting",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            IsTerminal = false,
                            Name = "Климат-контроль",
                            ParentId = 1,
                            ShortName = "climate-control",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            IsTerminal = false,
                            Name = "Источники света",
                            ParentId = 2,
                            ShortName = "light-sources",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            IsTerminal = false,
                            Name = "Управление освещением",
                            ParentId = 2,
                            ShortName = "lighting-control",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 6,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Датчики освещенности",
                            ParentId = 2,
                            ShortName = "light-sensors",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 7,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "LED лампы",
                            ParentId = 4,
                            ShortName = "led-lamps",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "RGB лампы",
                            ParentId = 4,
                            ShortName = "rgb-lamps",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 9,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Умные ленты",
                            ParentId = 4,
                            ShortName = "smart-strips",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Выключатели",
                            ParentId = 5,
                            ShortName = "switches",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 11,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Панели управления",
                            ParentId = 5,
                            ShortName = "control-panels",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 12,
                            IsTerminal = false,
                            Name = "Отопление",
                            ParentId = 3,
                            ShortName = "heating",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 13,
                            IsTerminal = false,
                            Name = "Охлаждение",
                            ParentId = 3,
                            ShortName = "cooling",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 14,
                            IsTerminal = false,
                            Name = "Вентиляция",
                            ParentId = 3,
                            ShortName = "ventilation",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 15,
                            IsTerminal = false,
                            Name = "Датчики климата",
                            ParentId = 3,
                            ShortName = "climate-sensors",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 16,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Термостаты",
                            ParentId = 12,
                            ShortName = "thermostats",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Радиаторные клапаны",
                            ParentId = 12,
                            ShortName = "radiator-valves",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            IsTerminal = true,
                            MeasureUnitId = 2,
                            Name = "Тёплый пол",
                            ParentId = 12,
                            ShortName = "floor-heating",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 19,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Кондиционеры",
                            ParentId = 13,
                            ShortName = "air-conditioners",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 20,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Вентиляторы",
                            ParentId = 13,
                            ShortName = "fans",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 21,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Рекуператоры",
                            ParentId = 14,
                            ShortName = "recuperators",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 22,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Вытяжные системы",
                            ParentId = 14,
                            ShortName = "exhaust-systems",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 23,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Датчики температуры",
                            ParentId = 15,
                            ShortName = "temperature-sensors",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 24,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "Датчики влажности",
                            ParentId = 15,
                            ShortName = "humidity-sensors",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 25,
                            IsTerminal = true,
                            MeasureUnitId = 1,
                            Name = "CO2 датчики",
                            ParentId = 15,
                            ShortName = "co2-sensors",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("SmartHome.Models.ClassParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassNodeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInherited")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxNumberValue")
                        .HasColumnType("numeric(18, 4)");

                    b.Property<decimal?>("MinNumberValue")
                        .HasColumnType("numeric(18, 4)");

                    b.Property<int>("ParameterDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParameterGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParameterDefinitionId");

                    b.HasIndex("ParameterGroupId");

                    b.HasIndex("ClassNodeId", "ParameterDefinitionId")
                        .IsUnique();

                    b.HasIndex("ClassNodeId", "SortOrder");

                    b.ToTable("class_parameter", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassNodeId = 7,
                            IsInherited = false,
                            IsRequired = true,
                            ParameterDefinitionId = 1,
                            ParameterGroupId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassNodeId = 7,
                            IsInherited = false,
                            IsRequired = true,
                            ParameterDefinitionId = 2,
                            ParameterGroupId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassNodeId = 7,
                            IsInherited = false,
                            IsRequired = true,
                            MaxNumberValue = 20m,
                            MinNumberValue = 3m,
                            ParameterDefinitionId = 3,
                            ParameterGroupId = 2,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ClassNodeId = 8,
                            IsInherited = false,
                            IsRequired = true,
                            ParameterDefinitionId = 2,
                            ParameterGroupId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            ClassNodeId = 8,
                            IsInherited = false,
                            IsRequired = true,
                            ParameterDefinitionId = 4,
                            ParameterGroupId = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 6,
                            ClassNodeId = 10,
                            IsInherited = false,
                            IsRequired = true,
                            ParameterDefinitionId = 1,
                            ParameterGroupId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 7,
                            ClassNodeId = 10,
                            IsInherited = false,
                            IsRequired = true,
                            MaxNumberValue = 6m,
                            MinNumberValue = 1m,
                            ParameterDefinitionId = 6,
                            ParameterGroupId = 3,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 8,
                            ClassNodeId = 16,
                            IsInherited = false,
                            IsRequired = true,
                            ParameterDefinitionId = 2,
                            ParameterGroupId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 9,
                            ClassNodeId = 16,
                            IsInherited = false,
                            IsRequired = true,
                            MaxNumberValue = 35m,
                            MinNumberValue = 5m,
                            ParameterDefinitionId = 7,
                            ParameterGroupId = 4,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 10,
                            ClassNodeId = 23,
                            IsInherited = false,
                            IsRequired = true,
                            ParameterDefinitionId = 2,
                            ParameterGroupId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 11,
                            ClassNodeId = 23,
                            IsInherited = false,
                            IsRequired = false,
                            ParameterDefinitionId = 8,
                            ParameterGroupId = 3,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 12,
                            ClassNodeId = 23,
                            IsInherited = false,
                            IsRequired = false,
                            ParameterDefinitionId = 9,
                            ParameterGroupId = 3,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("SmartHome.Models.EnumClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MeasureUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("enum_class", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Тип подключения",
                            ShortName = "connection-kind",
                            SortOrder = 1,
                            ValueType = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Протокол связи",
                            ShortName = "communication-protocol",
                            SortOrder = 2,
                            ValueType = 1
                        },
                        new
                        {
                            Id = 3,
                            MeasureUnitId = 5,
                            Name = "Мощность лампы",
                            ShortName = "lamp-power",
                            SortOrder = 3,
                            ValueType = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Иконка устройства",
                            ShortName = "device-icon",
                            SortOrder = 4,
                            ValueType = 3
                        });
                });

            modelBuilder.Entity("SmartHome.Models.EnumValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("EnumClassId")
                        .HasColumnType("integer");

                    b.Property<string>("IconValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal?>("NumberValue")
                        .HasColumnType("numeric(18, 4)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StringValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("EnumClassId");

                    b.HasIndex("EnumClassId", "SortOrder")
                        .IsUnique();

                    b.ToTable("enum_value", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Проводное подключение",
                            EnumClassId = 1,
                            SortOrder = 1,
                            StringValue = "Проводное"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Беспроводное подключение",
                            EnumClassId = 1,
                            SortOrder = 2,
                            StringValue = "Беспроводное"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Гибридное подключение",
                            EnumClassId = 1,
                            SortOrder = 3,
                            StringValue = "Гибридное"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Wi-Fi",
                            EnumClassId = 2,
                            SortOrder = 1,
                            StringValue = "Wi-Fi"
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Zigbee",
                            EnumClassId = 2,
                            SortOrder = 2,
                            StringValue = "Zigbee"
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Bluetooth",
                            EnumClassId = 2,
                            SortOrder = 3,
                            StringValue = "Bluetooth"
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "5 Вт",
                            EnumClassId = 3,
                            NumberValue = 5m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            DisplayName = "9 Вт",
                            EnumClassId = 3,
                            NumberValue = 9m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 9,
                            DisplayName = "12 Вт",
                            EnumClassId = 3,
                            NumberValue = 12m,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            DisplayName = "Лампочка",
                            EnumClassId = 4,
                            IconValue = "lightbulb",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 11,
                            DisplayName = "Термостат",
                            EnumClassId = 4,
                            IconValue = "thermostat",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 12,
                            DisplayName = "Камера",
                            EnumClassId = 4,
                            IconValue = "camera",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("SmartHome.Models.MeasureUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("measure_unit", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Штука",
                            ShortName = "шт."
                        },
                        new
                        {
                            Id = 2,
                            Name = "Комплект",
                            ShortName = "компл."
                        },
                        new
                        {
                            Id = 3,
                            Name = "Зона",
                            ShortName = "зона"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Канал",
                            ShortName = "канал"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ватт",
                            ShortName = "Вт"
                        });
                });

            modelBuilder.Entity("SmartHome.Models.ParameterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EnumClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("MeasureUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnumClassId");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.HasIndex("ValueType");

                    b.ToTable("parameter_definition", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnumClassId = 1,
                            Name = "Тип подключения",
                            ShortName = "connection-kind-param",
                            ValueType = 5
                        },
                        new
                        {
                            Id = 2,
                            EnumClassId = 2,
                            Name = "Протокол связи",
                            ShortName = "communication-protocol-param",
                            ValueType = 5
                        },
                        new
                        {
                            Id = 3,
                            MeasureUnitId = 5,
                            Name = "Мощность",
                            ShortName = "power-watt",
                            ValueType = 2
                        },
                        new
                        {
                            Id = 4,
                            EnumClassId = 3,
                            Name = "Мощность лампы из списка",
                            ShortName = "lamp-power-enum-param",
                            ValueType = 5
                        },
                        new
                        {
                            Id = 5,
                            EnumClassId = 4,
                            Name = "Иконка устройства",
                            ShortName = "device-icon-param",
                            ValueType = 5
                        },
                        new
                        {
                            Id = 6,
                            MeasureUnitId = 4,
                            Name = "Количество каналов",
                            ShortName = "channel-count",
                            ValueType = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Рабочая температура",
                            ShortName = "working-temperature",
                            ValueType = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Описание устройства",
                            ShortName = "device-description",
                            ValueType = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Дата ввода в эксплуатацию",
                            ShortName = "commissioning-date",
                            ValueType = 4
                        });
                });

            modelBuilder.Entity("SmartHome.Models.ParameterGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("parameter_group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Подключение",
                            ShortName = "connection",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Электропитание",
                            ShortName = "power",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Технические характеристики",
                            ShortName = "technical",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Климатические параметры",
                            ShortName = "climate",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Внешний вид",
                            ShortName = "appearance",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("SmartHome.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassNodeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ClassNodeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassNodeId = 7,
                            Name = "Xiaomi Smart LED Bulb",
                            ShortName = "xiaomi-led-bulb"
                        },
                        new
                        {
                            Id = 2,
                            ClassNodeId = 8,
                            Name = "Philips Hue White and Color",
                            ShortName = "philips-hue-color"
                        },
                        new
                        {
                            Id = 3,
                            ClassNodeId = 10,
                            Name = "Aqara Wall Switch H1",
                            ShortName = "aqara-switch-h1"
                        },
                        new
                        {
                            Id = 4,
                            ClassNodeId = 16,
                            Name = "Google Nest Thermostat",
                            ShortName = "nest-thermostat"
                        },
                        new
                        {
                            Id = 5,
                            ClassNodeId = 23,
                            Name = "Xiaomi Temperature and Humidity Sensor",
                            ShortName = "xiaomi-temp-humidity"
                        });
                });

            modelBuilder.Entity("SmartHome.Models.ProductParameterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassParameterId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateTimeValue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EnumValueId")
                        .HasColumnType("integer");

                    b.Property<int?>("IntegerValue")
                        .HasColumnType("integer");

                    b.Property<decimal?>("NumberValue")
                        .HasColumnType("numeric(18, 4)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("StringValue")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ClassParameterId");

                    b.HasIndex("EnumValueId");

                    b.HasIndex("ProductId", "ClassParameterId")
                        .IsUnique();

                    b.ToTable("product_parameter_value", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassParameterId = 1,
                            EnumValueId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassParameterId = 2,
                            EnumValueId = 4,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClassParameterId = 3,
                            NumberValue = 9m,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClassParameterId = 4,
                            EnumValueId = 5,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            ClassParameterId = 5,
                            EnumValueId = 8,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            ClassParameterId = 6,
                            EnumValueId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 7,
                            ClassParameterId = 7,
                            IntegerValue = 2,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 8,
                            ClassParameterId = 8,
                            EnumValueId = 4,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 9,
                            ClassParameterId = 9,
                            NumberValue = 25m,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 10,
                            ClassParameterId = 10,
                            EnumValueId = 5,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 11,
                            ClassParameterId = 11,
                            ProductId = 5,
                            StringValue = "Датчик температуры и влажности для системы умного дома"
                        });
                });

            modelBuilder.Entity("SmartHome.Models.ClassNode", b =>
                {
                    b.HasOne("SmartHome.Models.MeasureUnit", "MeasureUnit")
                        .WithMany("ClassNodes")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartHome.Models.ClassNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MeasureUnit");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SmartHome.Models.ClassParameter", b =>
                {
                    b.HasOne("SmartHome.Models.ClassNode", "ClassNode")
                        .WithMany("ClassParameters")
                        .HasForeignKey("ClassNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHome.Models.ParameterDefinition", "ParameterDefinition")
                        .WithMany("ClassParameters")
                        .HasForeignKey("ParameterDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHome.Models.ParameterGroup", "ParameterGroup")
                        .WithMany("ClassParameters")
                        .HasForeignKey("ParameterGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClassNode");

                    b.Navigation("ParameterDefinition");

                    b.Navigation("ParameterGroup");
                });

            modelBuilder.Entity("SmartHome.Models.EnumClass", b =>
                {
                    b.HasOne("SmartHome.Models.MeasureUnit", "MeasureUnit")
                        .WithMany("EnumClasses")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MeasureUnit");
                });

            modelBuilder.Entity("SmartHome.Models.EnumValue", b =>
                {
                    b.HasOne("SmartHome.Models.EnumClass", "EnumClass")
                        .WithMany("Values")
                        .HasForeignKey("EnumClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnumClass");
                });

            modelBuilder.Entity("SmartHome.Models.ParameterDefinition", b =>
                {
                    b.HasOne("SmartHome.Models.EnumClass", "EnumClass")
                        .WithMany("ParameterDefinitions")
                        .HasForeignKey("EnumClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartHome.Models.MeasureUnit", "MeasureUnit")
                        .WithMany("ParameterDefinitions")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EnumClass");

                    b.Navigation("MeasureUnit");
                });

            modelBuilder.Entity("SmartHome.Models.Product", b =>
                {
                    b.HasOne("SmartHome.Models.ClassNode", "ClassNode")
                        .WithMany("Products")
                        .HasForeignKey("ClassNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassNode");
                });

            modelBuilder.Entity("SmartHome.Models.ProductParameterValue", b =>
                {
                    b.HasOne("SmartHome.Models.ClassParameter", "ClassParameter")
                        .WithMany("ProductValues")
                        .HasForeignKey("ClassParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHome.Models.EnumValue", "EnumValue")
                        .WithMany("ProductParameterValues")
                        .HasForeignKey("EnumValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartHome.Models.Product", "Product")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassParameter");

                    b.Navigation("EnumValue");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartHome.Models.ClassNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ClassParameters");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartHome.Models.ClassParameter", b =>
                {
                    b.Navigation("ProductValues");
                });

            modelBuilder.Entity("SmartHome.Models.EnumClass", b =>
                {
                    b.Navigation("ParameterDefinitions");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("SmartHome.Models.EnumValue", b =>
                {
                    b.Navigation("ProductParameterValues");
                });

            modelBuilder.Entity("SmartHome.Models.MeasureUnit", b =>
                {
                    b.Navigation("ClassNodes");

                    b.Navigation("EnumClasses");

                    b.Navigation("ParameterDefinitions");
                });

            modelBuilder.Entity("SmartHome.Models.ParameterDefinition", b =>
                {
                    b.Navigation("ClassParameters");
                });

            modelBuilder.Entity("SmartHome.Models.ParameterGroup", b =>
                {
                    b.Navigation("ClassParameters");
                });

            modelBuilder.Entity("SmartHome.Models.Product", b =>
                {
                    b.Navigation("ParameterValues");
                });
#pragma warning restore 612, 618
        }
    }
}
